# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37f6429aeabde8c6f8d520c6ef71144d2b3763100c01107f99972b762cb86d944c9695b0aa63c137af7dbb78c6f3f063356be89ef67031074a1c9d4e0d0aa70b

test:
  secret_key_base: b195d7fb674cc7a756d56a465ac62465204395ecc9594fef03afd2dd3680eefd45aeb32d877e9581df8f320cf0826519080ade729b1e09104754ddfb7f206379

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
